### ISSUE TITLE
Add pattern measure navigation /left/right

### ISSUE THREAD

**Issue by teotidev** [teotidev/ltm#18]
Turned into a control overlay
- PatternSelectControl
- NavigationPadControl

---

Try a popup with 4 arrows to navigate left/right, up/down.

Left/Right - selectedViewBar
Up/Down - octave +/-

The action button should be the last child in the toolbar when landscape and the first child when portrait for left thumb access.

**Comment by teotigraphix** [comment]
imple with scroll
